// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5XnWSO38Ov4fksj_euyR21jFJQIr8JaM',
    appId: '1:191349063904:web:71a5778d8d01997e9e9085',
    messagingSenderId: '191349063904',
    projectId: 'mobileappdate-edf6a',
    authDomain: 'mobileappdate-edf6a.firebaseapp.com',
    storageBucket: 'mobileappdate-edf6a.firebasestorage.app',
    measurementId: 'G-6FM5266VN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwv5iAAGv1s1mTMRS5EsTvKzFrNRkufGs',
    appId: '1:191349063904:android:6a894c383d31c8d99e9085',
    messagingSenderId: '191349063904',
    projectId: 'mobileappdate-edf6a',
    storageBucket: 'mobileappdate-edf6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVMOiB2q7wvzlSF7wxW3rYeXc3ejkB7oI',
    appId: '1:191349063904:ios:017c83aa0995b6699e9085',
    messagingSenderId: '191349063904',
    projectId: 'mobileappdate-edf6a',
    storageBucket: 'mobileappdate-edf6a.firebasestorage.app',
    iosBundleId: 'com.example.restaurantFinderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVMOiB2q7wvzlSF7wxW3rYeXc3ejkB7oI',
    appId: '1:191349063904:ios:017c83aa0995b6699e9085',
    messagingSenderId: '191349063904',
    projectId: 'mobileappdate-edf6a',
    storageBucket: 'mobileappdate-edf6a.firebasestorage.app',
    iosBundleId: 'com.example.restaurantFinderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5XnWSO38Ov4fksj_euyR21jFJQIr8JaM',
    appId: '1:191349063904:web:e5237ef8005721a39e9085',
    messagingSenderId: '191349063904',
    projectId: 'mobileappdate-edf6a',
    authDomain: 'mobileappdate-edf6a.firebaseapp.com',
    storageBucket: 'mobileappdate-edf6a.firebasestorage.app',
    measurementId: 'G-0J7HGG080P',
  );
}
